/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Address {
  'country' : string,
  'city' : string,
  'name' : string,
  'zipcode' : string,
  'addressLine1' : string,
  'addressLine2' : [] | [string],
  'phoneNumber' : [] | [string],
}
export interface Cart {
  'email' : [] | [string],
  'shippingAddress' : [] | [Address],
  'items' : Array<CartItem>,
  'totalPrice' : Money,
}
export interface CartItem { 'quantity' : bigint, 'product' : Product }
export interface Money { 'value' : bigint, 'currency' : string }
export interface Order {
  'id' : bigint,
  'owner' : Principal,
  'cart' : Cart,
  'paid' : boolean,
  'anonymous' : boolean,
  'customerAddress' : Address,
  'timestamp' : bigint,
}
export interface Product {
  'id' : bigint,
  'sku' : string,
  'title' : string,
  'description' : [] | [string],
  'stock' : bigint,
  'category' : string,
  'price' : Money,
}
export interface UserProfile {
  'name' : string,
  'email' : [] | [string],
  'defaultAddress' : [] | [Address],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<[Product], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createOrder' : ActorMethod<[Cart, Address], bigint>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyOrders' : ActorMethod<[], Array<Order>>,
  'getOrder' : ActorMethod<[bigint], [] | [Order]>,
  'getOrdersByAddress' : ActorMethod<[Address], Array<Order>>,
  'getOrdersByProductId' : ActorMethod<[bigint], Array<Order>>,
  'getOrdersByStatus' : ActorMethod<[boolean], Array<Order>>,
  'getProduct' : ActorMethod<[bigint], [] | [Product]>,
  'getProductsByCategory' : ActorMethod<[string], Array<Product>>,
  'getProductsByCategorySorted' : ActorMethod<
    [string, string, boolean],
    Array<Product>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchProducts' : ActorMethod<[string], Array<Product>>,
  'updateOrderStatus' : ActorMethod<[bigint, boolean], undefined>,
  'updateProduct' : ActorMethod<[bigint, Product], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];