/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Money = IDL.Record({ 'value' : IDL.Nat, 'currency' : IDL.Text });
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'sku' : IDL.Text,
  'title' : IDL.Text,
  'description' : IDL.Opt(IDL.Text),
  'stock' : IDL.Nat,
  'category' : IDL.Text,
  'price' : Money,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Address = IDL.Record({
  'country' : IDL.Text,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'zipcode' : IDL.Text,
  'addressLine1' : IDL.Text,
  'addressLine2' : IDL.Opt(IDL.Text),
  'phoneNumber' : IDL.Opt(IDL.Text),
});
export const CartItem = IDL.Record({
  'quantity' : IDL.Nat,
  'product' : Product,
});
export const Cart = IDL.Record({
  'email' : IDL.Opt(IDL.Text),
  'shippingAddress' : IDL.Opt(Address),
  'items' : IDL.Vec(CartItem),
  'totalPrice' : Money,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'owner' : IDL.Principal,
  'cart' : Cart,
  'paid' : IDL.Bool,
  'anonymous' : IDL.Bool,
  'customerAddress' : Address,
  'timestamp' : IDL.Int,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'defaultAddress' : IDL.Opt(Address),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addProduct' : IDL.Func([Product], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createOrder' : IDL.Func([Cart, Address], [IDL.Nat], []),
  'deleteProduct' : IDL.Func([IDL.Nat], [], []),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getOrder' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
  'getOrdersByAddress' : IDL.Func([Address], [IDL.Vec(Order)], ['query']),
  'getOrdersByProductId' : IDL.Func([IDL.Nat], [IDL.Vec(Order)], ['query']),
  'getOrdersByStatus' : IDL.Func([IDL.Bool], [IDL.Vec(Order)], ['query']),
  'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
  'getProductsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'getProductsByCategorySorted' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Bool],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'updateOrderStatus' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'updateProduct' : IDL.Func([IDL.Nat, Product], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Money = IDL.Record({ 'value' : IDL.Nat, 'currency' : IDL.Text });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'sku' : IDL.Text,
    'title' : IDL.Text,
    'description' : IDL.Opt(IDL.Text),
    'stock' : IDL.Nat,
    'category' : IDL.Text,
    'price' : Money,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Address = IDL.Record({
    'country' : IDL.Text,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'zipcode' : IDL.Text,
    'addressLine1' : IDL.Text,
    'addressLine2' : IDL.Opt(IDL.Text),
    'phoneNumber' : IDL.Opt(IDL.Text),
  });
  const CartItem = IDL.Record({ 'quantity' : IDL.Nat, 'product' : Product });
  const Cart = IDL.Record({
    'email' : IDL.Opt(IDL.Text),
    'shippingAddress' : IDL.Opt(Address),
    'items' : IDL.Vec(CartItem),
    'totalPrice' : Money,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'owner' : IDL.Principal,
    'cart' : Cart,
    'paid' : IDL.Bool,
    'anonymous' : IDL.Bool,
    'customerAddress' : Address,
    'timestamp' : IDL.Int,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'defaultAddress' : IDL.Opt(Address),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addProduct' : IDL.Func([Product], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createOrder' : IDL.Func([Cart, Address], [IDL.Nat], []),
    'deleteProduct' : IDL.Func([IDL.Nat], [], []),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getOrder' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
    'getOrdersByAddress' : IDL.Func([Address], [IDL.Vec(Order)], ['query']),
    'getOrdersByProductId' : IDL.Func([IDL.Nat], [IDL.Vec(Order)], ['query']),
    'getOrdersByStatus' : IDL.Func([IDL.Bool], [IDL.Vec(Order)], ['query']),
    'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getProductsByCategorySorted' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Bool],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
    'updateOrderStatus' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'updateProduct' : IDL.Func([IDL.Nat, Product], [], []),
  });
};

export const init = ({ IDL }) => { return []; };